apiVersion: v1
kind: Namespace
metadata:
  name: jpglabs
  labels:
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-services
  labels:
    app.kubernetes.io/managed-by: kubectl
